name: Lint (mypy and flake8)

on: [push]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U pip setuptools wheel
        pip install -e '.[lint]'
    - name: Lint using flake8 and mypy
      run: |
        flake8 muve/ tests/
        mypy
